### ISSUE TITLE
[MainTask] KM編輯功能

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/MerMer-official#83]
# 任務

## 流程大綱
- 文件撰寫一週
- 程式撰寫3週

## Link
- [Figma wireframe](https://www.figma.com/file/YQXgk6rcdULiVDKgCPqcbb/MerMer-official-web?type=design&node-id=591-6687&mode=design&t=GbYxB3acdAwKdYSw-0)
- [需求規格書](https://docs.google.com/document/d/13vfEOLeDd_cm1gek9-FUa0qspWzkg24b8mmhMCTIv4c/edit)
- [系統架構書](https://docs.google.com/document/d/1KpeaQ31RcYn91rvhDpjcrrVT2C8JhA0aa0ePZYRF2tY/edit)
- 開發規格書
    - [Persona 人物誌](https://drive.google.com/file/d/1gKI9jHeX7CwbpWz-6kuzfoDwzfCHVJLI/view)
    - [User story](https://docs.google.com/document/d/13hulzhdA_dQ39m6zb2BeG_egSrbl7Gu9o2tiqiOmldw/edit?usp=sharing)
    - [User Journey Map](https://drive.google.com/file/d/1Rcm3SUC-zFMCyXgF_oDJT8D_BXb3EP7k/view?usp=sharing)
    - UML
        - [Class Diagram draw.io file](https://drive.google.com/file/d/1eeHCpbklV2Dp385pXvzEKy4muydzuR8E/view?usp=sharing)
        - [Component Diagram draw.io file](https://drive.google.com/file/d/1-S_Gysa1MiL5ht3pFfpEVrSTPnb7viYY/view?usp=sharing)
        - [Sequence Diagram draw.io file](https://drive.google.com/file/d/1UAKPVTDfonXcrU_gsf-o0xY6K9MjI9X2/view?usp=sharing)
    - [DB Schema](https://dbdiagram.io/d/KM-Editor-659f6087ac844320aead0967)
### 需求規格書 -4pt
- [x] #84  成品： [需求規格書](https://docs.google.com/document/d/13vfEOLeDd_cm1gek9-FUa0qspWzkg24b8mmhMCTIv4c/edit) -4pt

### 系統規劃書 -8pt
- [x] #86 -4pt
- [x] #87 -4pt

### 開發規格文件 -21pt
 - [x] #88 成品： [Persona 人物誌](https://drive.google.com/file/d/1gKI9jHeX7CwbpWz-6kuzfoDwzfCHVJLI/view) -2pt
 - [x] #89 成品： [User story](https://docs.google.com/document/d/13hulzhdA_dQ39m6zb2BeG_egSrbl7Gu9o2tiqiOmldw/edit?usp=sharing) -1pt
 - [x] #90 成品：[User Journey Map](https://drive.google.com/file/d/1Rcm3SUC-zFMCyXgF_oDJT8D_BXb3EP7k/view?usp=sharing) -4pt
 - [x] UML -12pt
	 - [x] #91 -4pt
	 - [x] #92 -4pt
	 - [x] #93 -4pt
- [x] #94 -2pt

### 登入系統 -27pt
---

- [x] #96 -4pt
- [x] #97 -4pt
- [x] #99 -5pt
- [x] #98 -4pt
- [x] #101 -3pt
- [x] #102 -5pt

### 瀏覽畫面 -24pt
---
#### 前端 -15pt
- [x] #103 -2pt
- [x] #104 -3pt
- [x] #105 -2pt
- [x] #106 -3pt
- [x] #107 -3pt
- [x] #130 -2pt

##### 後端 -12pt
- [x] #110 -3pt
- [x] #109 -3pt
- [x] #121 -3pt

### 編輯畫面 -30pt
---
#### 前端 -16pt
- [x] #111 -2pt
- [x] #112 -2pt
- [x] #113 -5pt
- [x] #114 -3pt
- [x] #115 -2pt
- [x] #116 -2pt
- [x] #125 -4pt
- [x] #147 -5pt
- [x] #149 -3pt

#### 後端 -24pt
- [x] #117 -2pt
- [x] #131 -5pt
- [x] #118 -2pt
- [x] #120 -5pt
- [x] #126 -5pt
- [x] #137 -2pt

### 其他 -16pt
- [x] #132 -8pt
- [x] #133 -8pt
- [x] #141 -3pt
- [x] #143 -3pt
- [x] #144 -3pt
- [x] #145 -3pt
- [x] #150 -3pt
- [x] #162 -8pt

**Comment by TinyMurky** [comment]
## 規劃
- 文件撰寫一周約 23 hr
- 編寫程式碼三週約 120 hr

## 目前進度：
### 已完成
<格式：單號/總計時間>
None

### 進行中
<格式：單號/目前已進行時間>

花費時間為：xx hr

**Comment by TinyMurky** [comment]
done
